{"stats": {"errors": 3, "failures": 0, "passes": 0, "skipped": 0, "encoding": "UTF-8", "total": 3}, "results": [{"classname": "index_test:TestPythonLoops", "name": "test_city_indices_list", "time": 0.0002579689025878906, "type": "error", "errtype": "builtins.NameError", "message": "name 'city_indices' is not defined", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 67, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 625, in run\n    testMethod()\n  File \"/home/tjcarney89/function-arguments-lab-data-science-alpha/test/index_test.py\", line 13, in test_city_indices_list\n    self.assertEqual(city_indices, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])\nNameError: name 'city_indices' is not defined\n"}, {"classname": "index_test:TestPythonLoops", "name": "test_city_populations", "time": 0.0001437664031982422, "type": "error", "errtype": "builtins.NameError", "message": "name 'city_areas' is not defined", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 67, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 625, in run\n    testMethod()\n  File \"/home/tjcarney89/function-arguments-lab-data-science-alpha/test/index_test.py\", line 19, in test_city_populations\n    self.assertEqual(city_areas, [59, 68, 4758, 3750, 33, 200, 491, 8300, 672, 27, 2731571, 3194])\nNameError: name 'city_areas' is not defined\n"}, {"classname": "index_test:TestPythonLoops", "name": "test_names_and_ranks_list", "time": 0.00012540817260742188, "type": "error", "errtype": "builtins.NameError", "message": "name 'names_and_ranks' is not defined", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 67, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 625, in run\n    testMethod()\n  File \"/home/tjcarney89/function-arguments-lab-data-science-alpha/test/index_test.py\", line 9, in test_names_and_ranks_list\n    self.assertEqual(names_and_ranks[0], '1. Solta')\nNameError: name 'names_and_ranks' is not defined\n"}]}